# Generated by Django 2.2.6 on 2019-10-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_labeling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='answer_time',
            field=models.FloatField(),
        ),
    ]
